### ISSUE TITLE
[Feature Request] Add pagination support

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [fuxingloh/vue-horizontal#89]
Will it be possible to add support for pagination element? Such as this one: 
![image](https://user-images.githubusercontent.com/2766448/105579857-1b578780-5d9a-11eb-8d71-c0418ee3e89d.png)
It would be also great if things like active item index would also be exposed on API level

**Comment by fuxingloh** [comment]
I tried to avoid adding support for complex features internally but made it easy to extend features externally with the exposed API. I thought it's better that way to reduce code smell and library complexity while allowing flexibility.

I have actually documented how you can add pagination support here https://vue-horizontal.fuxing.dev/recipes/carousel

While for active item index, you can use `IntersectionObserver` which is also mentioned in the carousel doc page.

**Comment by fuxingloh** [comment]
I just added a new example in the documentation; very similar to the image you provided.

You can take a look at it here: https://deploy-preview-90--vue-horizontal.netlify.app/recipes/pagination/

**Comment by AndrewBogdanovTSS** [comment]
Great, thanks 👍🏻
